---
title: "Building a basic chain-SIR model"
author: "Pablo Perez"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: word_document
---

A chain-SIR model can simulate S→I→R flows with 'realistic'
infectious period distributions (u), where:
    k(t −τ ) is the number of individuals infected τ time units ago,
    h(τ ) is the probability of recovering on infection-day τ , and
    H(τ ) is the cumulative probability of having recovered by infection-day τ

k(t −τ )/(1−H(τ )) thus represents the fraction of individuals infected
at time t−τ that still remains in the infected class on day t and the integral is 
over all previous infections so as to quantify the total flux into the removed 
class at time t.


```{r}
chainSIR=function(t, logx, params){
  x=exp(logx)
  u=params["u"]
  S=x[1]
  I=x[2:(u+1)]
  R=x[u+2]
  with(as.list(params),{
    dS = mu * (N - S) - sum(beta * S * I) / N
    dI = rep(0, u)
    dI[1] = sum(beta * S * I) / N - (mu + u*gamma) * I[1]
    if(u>1){
      for(i in 2:u){
        dI[i]= u*gamma * I[i-1] - (mu+u*gamma)* I[i]
      }
    }
    dR = u*gamma * I[u] - mu * R
    res=c(dS/S, dI/I, dR/R)
    list(res)
  })
}

times = seq(0, 10, by=1/52)
paras2 = c(mu = 1/75, N = 1, beta = 625,
           gamma = 365/14, u=1)
xstart2 = log(c(S=.06, I=c(0.001, rep(0.0001,
                                      paras2["u"]-1)), R = 0.0001))
out = as.data.frame(deSolve::ode(xstart2, times, chainSIR,
                        paras2))
plot(times, exp(out[,3]), ylab="Infected", xlab=
       "Time", ylim=c(0, 0.01), type="l")
paras2["u"] =2
xstart2 = log(c(S=.06, I=c(0.001, rep(0.0001/
                                        paras2["u"], paras2["u"]-1)), R = 0.0001))
out2 = as.data.frame(deSolve::ode(xstart2, times, chainSIR,
                         paras2))
lines(times, apply(exp(out2[,-c(1:2,length(out2))]),
                   1 ,sum), col="blue")
paras2["u"] =73
xstart2 = log(c(S=.06, I=c(0.001, rep(0.0001/
                                        paras2["u"], paras2["u"]-1)), R = 0.0001))
out3 = as.data.frame(deSolve::ode(xstart2, times, chainSIR,
                         paras2))
lines(times, apply(exp(out3[,-c(1:2,length(out3))]),
                   1, sum), col="red", lwd=2, lty=2)
paras2["u"] =500
xstart2 = log(c(S=.06, I=c(0.001, rep(0.0001/
                                        paras2["u"], paras2["u"]-1)), R = 0.0001))
out4 = as.data.frame(deSolve::ode(xstart2, times, chainSIR,
                         paras2))
lines(times, apply(exp(out4[,-c(1:2,length(out4))]),
                   1,sum, na.rm=TRUE), col="green")

legend("topright", legend=c("SIR", "u=2", "u=500",
                            "u=73 (H-S)"), lty=c(1,1,1,2), lwd=c(1,1,1, 2),
       col=c("black", "blue", "green", "red"))
```

The narrower the infectious-period distribution, the more punctuated the predicted
epidemics. However, infectious-period narrowing alone cannot sustain
recurrent epidemics. In the absence of stochastic or seasonal forcing, epidemics will
dampen to the endemic equilibrium (though the damping period is slightly accelerated
and the convergence on the equilibrium is slightly slower with narrowing
infectious period distributions).